### ISSUE TITLE
Nested index.php

### ISSUE THREAD

**Issue by jhadvig** [openshift/sti-php#16]
What if the `index.php` is nested, eg: /opt/openshift/src/public/index.php then the Apache can't serve it cause its expecting the index.php in the `/opt/openshift/src` dir due to the https://github.com/openshift/sti-php/blob/master/5.5/contrib/httpdconf.sed#L4

We need to come with a way how to specify the DocumentRoot, something like a `context-dir` ...

**Comment by jhadvig** [comment]
@bparees @csrwng @mfojtik @mnagy fyi

**Comment by bparees** [comment]
is this any different than v2 behavior?  shouldn't index.php end up served as "host.com/public/index.php" in your scenario?

**Comment by jhadvig** [comment]
@bparees well as we spoke, in v2 you are able to detect the document root, where the index.php is located http://docs.openshift.org/origin-m4/oo_cartridge_guide.html#document-root 
Unfortunately this cant be done with our approach since we dont know how the application looks like upon the php-55-***7 image build. In that case we have to come with a solution that will supply user with possibility to change the DocumentRoot.
A simple fix would be to add `151s%AllowOverride None%AllowOverride All%` to the end of httdconf.sed which will take additional instructions for a[ache from `.htaccess` file which user will have to supply.

**Comment by jhadvig** [comment]
basically here are the changes I had to make: https://github.com/openshift/sti-php/compare/master...jhadvig:laravel5?expand=1

**Comment by mfojtik** [comment]
@jhadvig @bparees why we can't set AllowOverride All by default? Is there a security concern here?

**Comment by mfojtik** [comment]
@jhadvig in your diff, you also installing 'git' which I think is now included in base

**Comment by jhadvig** [comment]
@mfojtik it is, we can leave that out of discussion. Regarding setting the `AllowOverride All`, if you look closer to that change it only applies to the line 151 in the httpd.conf, and which allows reading the `.htaccess` file in the `opt/openshift/src` directory, which for now I think would be the best solution. In that case the `index.php` could be nested inside the repo and user will just have to supply the `.htaccess` to the root of the repo so Apache can pick up the information from it.

**Comment by bparees** [comment]
@jhadvig sounds ok to me.

**Comment by jhadvig** [comment]
@bparees ok will send PR + update docs accordingly

**Comment by jhadvig** [comment]
https://github.com/openshift/sti-php/pull/19
