### ISSUE TITLE
Wrong Session path

### ISSUE THREAD

**Issue by derdanu** [openshift/sti-php#51]
In the file /opt/rh/httpd24/root/etc/httpd/conf.d/php55-php.conf the default session path will be set. 
This directory is not writable when running a container on ose3 environment in non priviledged mode. 

For a fix see pull request #49 #50

**Comment by derdanu** [comment]
Both PR are merged in PR #53 now.

**Comment by mfojtik** [comment]
@derdanu thanks for fixing this!
